import {
  EnumTaskPriority,
  EnumTaskStatus,
  EnumTaskTag,
  ITask,
} from './tasks.model';

export const tasksDatabase: ITask[] = [
  {
    id: 'a1b2c3d4-1111-4111-a111-a1b2c3d4e5f1',
    title: 'Complete project documentation',
    description:
      'Write comprehensive documentation for the API endpoints, including request/response examples and error handling.',
    tags: [EnumTaskTag.WORK, EnumTaskTag.EDUCATION],
    priority: EnumTaskPriority.HIGH,
    status: EnumTaskStatus.IN_PROGRESS,
    createdAt: new Date('2025-01-10T10:00:00Z'),
    updatedAt: new Date('2025-01-15T14:30:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-2222-4222-a222-a1b2c3d4e5f2',
    title: 'Grocery shopping for the week',
    description:
      'Buy vegetables, fruits, dairy products, and household essentials. Check pantry inventory first.',
    tags: [EnumTaskTag.SHOPPING, EnumTaskTag.FOOD, EnumTaskTag.HOME],
    priority: EnumTaskPriority.MEDIUM,
    status: EnumTaskStatus.TODO,
    createdAt: new Date('2025-01-12T08:00:00Z'),
    updatedAt: new Date('2025-01-12T08:00:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-3333-4333-a333-a1b2c3d4e5f3',
    title: 'Schedule annual health checkup',
    description:
      'Book appointment with family doctor for routine physical examination and blood tests.',
    tags: [EnumTaskTag.HEALTH, EnumTaskTag.PERSONAL],
    priority: EnumTaskPriority.HIGH,
    status: EnumTaskStatus.DONE,
    createdAt: new Date('2025-01-05T09:00:00Z'),
    updatedAt: new Date('2025-01-08T11:00:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-4444-4444-a444-a1b2c3d4e5f4',
    title: 'Plan summer vacation trip',
    description:
      'Research destinations, compare flight prices, book hotel accommodations, and create itinerary.',
    tags: [EnumTaskTag.TRAVEL, EnumTaskTag.FAMILY, EnumTaskTag.FINANCE],
    priority: EnumTaskPriority.MEDIUM,
    status: EnumTaskStatus.IN_PROGRESS,
    createdAt: new Date('2025-01-08T15:00:00Z'),
    updatedAt: new Date('2025-01-14T10:20:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-5555-4555-a555-a1b2c3d4e5f5',
    title: 'Take car for oil change and inspection',
    description:
      'Schedule service appointment at the dealership. Check tire pressure and fluid levels.',
    tags: [EnumTaskTag.CAR, EnumTaskTag.PERSONAL],
    priority: EnumTaskPriority.MEDIUM,
    status: EnumTaskStatus.TODO,
    createdAt: new Date('2025-01-13T07:30:00Z'),
    updatedAt: new Date('2025-01-13T07:30:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-6666-4666-a666-a1b2c3d4e5f6',
    title: 'Organize birthday party for daughter',
    description:
      'Send invitations, order cake, plan activities, and prepare decorations. Theme: Princess party.',
    tags: [EnumTaskTag.FAMILY, EnumTaskTag.SOCIAL, EnumTaskTag.SHOPPING],
    priority: EnumTaskPriority.HIGH,
    status: EnumTaskStatus.IN_PROGRESS,
    createdAt: new Date('2025-01-10T12:00:00Z'),
    updatedAt: new Date('2025-01-15T16:45:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-7777-4777-a777-a1b2c3d4e5f7',
    title: 'Learn TypeScript advanced patterns',
    description:
      'Complete online course on generics, decorators, and advanced type manipulation. Practice with coding exercises.',
    tags: [EnumTaskTag.EDUCATION, EnumTaskTag.WORK, EnumTaskTag.PERSONAL],
    priority: EnumTaskPriority.MEDIUM,
    status: EnumTaskStatus.TODO,
    createdAt: new Date('2025-01-11T14:00:00Z'),
    updatedAt: new Date('2025-01-11T14:00:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-8888-4888-a888-a1b2c3d4e5f8',
    title: 'Take dog to veterinarian for vaccination',
    description:
      'Annual checkup and update vaccinations. Ask about dental cleaning schedule.',
    tags: [EnumTaskTag.PET, EnumTaskTag.HEALTH],
    priority: EnumTaskPriority.MEDIUM,
    status: EnumTaskStatus.DONE,
    createdAt: new Date('2025-01-07T09:00:00Z'),
    updatedAt: new Date('2025-01-09T13:30:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-9999-4999-a999-a1b2c3d4e5f9',
    title: 'Review monthly budget and expenses',
    description:
      'Analyze spending patterns, update budget categories, and plan for upcoming expenses. Review credit card statements.',
    tags: [EnumTaskTag.FINANCE, EnumTaskTag.PERSONAL],
    priority: EnumTaskPriority.HIGH,
    status: EnumTaskStatus.TODO,
    createdAt: new Date('2025-01-14T08:00:00Z'),
    updatedAt: new Date('2025-01-14T08:00:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-aaaa-4aaa-aaaa-a1b2c3d4e5fa',
    title: 'Prepare dinner for friends gathering',
    description:
      'Plan menu, buy ingredients, and cook main course. Set up dining area and prepare appetizers.',
    tags: [EnumTaskTag.FOOD, EnumTaskTag.SOCIAL, EnumTaskTag.HOME],
    priority: EnumTaskPriority.MEDIUM,
    status: EnumTaskStatus.IN_PROGRESS,
    createdAt: new Date('2025-01-13T10:00:00Z'),
    updatedAt: new Date('2025-01-15T17:00:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-bbbb-4bbb-bbbb-a1b2c3d4e5fb',
    title: 'Finish reading "Clean Code" book',
    description:
      'Complete remaining chapters on error handling and concurrency. Take notes on best practices.',
    tags: [EnumTaskTag.EDUCATION, EnumTaskTag.WORK],
    priority: EnumTaskPriority.LOW,
    status: EnumTaskStatus.IN_PROGRESS,
    createdAt: new Date('2025-01-06T16:00:00Z'),
    updatedAt: new Date('2025-01-14T20:00:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-cccc-4ccc-cccc-a1b2c3d4e5fc',
    title: 'Go for morning jog in the park',
    description:
      'Run 5km route around the park. Focus on maintaining steady pace and proper breathing technique.',
    tags: [EnumTaskTag.SPORT, EnumTaskTag.HEALTH, EnumTaskTag.PERSONAL],
    priority: EnumTaskPriority.MEDIUM,
    status: EnumTaskStatus.TODO,
    createdAt: new Date('2025-01-15T06:00:00Z'),
    updatedAt: new Date('2025-01-15T06:00:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-dddd-4ddd-dddd-a1b2c3d4e5fd',
    title: 'Fix leaking kitchen faucet',
    description:
      'Replace worn-out washer and check water pressure. May need to call plumber if issue persists.',
    tags: [EnumTaskTag.HOME, EnumTaskTag.PERSONAL],
    priority: EnumTaskPriority.HIGH,
    status: EnumTaskStatus.TODO,
    createdAt: new Date('2025-01-14T11:00:00Z'),
    updatedAt: new Date('2025-01-14T11:00:00Z'),
    isBlocked: true,
  },
  {
    id: 'a1b2c3d4-eeee-4eee-eeee-a1b2c3d4e5fe',
    title: 'Practice guitar for upcoming concert',
    description:
      'Rehearse setlist of 10 songs. Focus on smooth transitions between songs and stage presence.',
    tags: [EnumTaskTag.HOBBY, EnumTaskTag.PERSONAL, EnumTaskTag.SOCIAL],
    priority: EnumTaskPriority.MEDIUM,
    status: EnumTaskStatus.IN_PROGRESS,
    createdAt: new Date('2025-01-09T18:00:00Z'),
    updatedAt: new Date('2025-01-15T19:30:00Z'),
    isBlocked: false,
  },
  {
    id: 'a1b2c3d4-ffff-4fff-ffff-a1b2c3d4e5ff',
    title: 'Attend team building event',
    description:
      'Participate in company team building activities. Network with colleagues and enjoy team lunch.',
    tags: [EnumTaskTag.WORK, EnumTaskTag.SOCIAL],
    priority: EnumTaskPriority.LOW,
    status: EnumTaskStatus.DONE,
    createdAt: new Date('2025-01-08T13:00:00Z'),
    updatedAt: new Date('2025-01-10T18:00:00Z'),
    isBlocked: false,
  },
];
